---
- name: Shutdown All Linux Servers
  hosts: all
  become: yes
  tasks:
    - name: Shutdown the server
      ansible.builtin.command: /sbin/shutdown -h now
      ignore_errors: yes  # This prevents AWX from marking the job as "failed"
