---
- name: Shutdown All Linux Servers
  hosts: all
  become: yes
  tasks:
    - name: Notify about shutdown
      debug:
        msg: "Shutting down the server in 5 seconds..."

    - name: Wait for 5 seconds
      ansible.builtin.pause:
        seconds: 5

    - name: Shutdown the server
      ansible.builtin.command: /sbin/shutdown -h now
      ignore_errors: yes
